[package]
name = "pdf-reader"
description = "Privacy-first, offline desktop PDF reader"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[lib]
name = "pdf_reader_lib"

[build-dependencies]
tauri-build.workspace = true

[dependencies]
tauri.workspace = true

[lints]
workspace = true
