//! Generates `src/ipc/generated/contract.ts`: TypeScript declarations for every frontend-visible
//! type plus the limits and raster constants, so both languages share one source of truth.
//!
//! Regenerate with `pnpm ipc:generate`. The `generated_typescript_is_up_to_date` test fails
//! (and with it CI) whenever the committed file differs from what this module produces.

use std::path::PathBuf;

use ts_rs::{Config, TS};

use crate::limits::*;
use crate::raster::{RASTER_FORMAT_RGBA8, RASTER_HEADER_BYTES, RASTER_MAGIC};
use crate::types::*;

const HEADER: &str = "\
// Generated by `pnpm ipc:generate` from crates/ipc_contract. Do not edit by hand.
// See docs/architecture/ipc-contract.md.
";

/// Path of the generated file, relative to this crate.
pub fn output_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../src/ipc/generated/contract.ts")
}

/// The complete contents of the generated TypeScript file.
pub fn bindings() -> String {
    let cfg = Config::new();
    let mut out = String::from(HEADER);

    macro_rules! declare {
        ($($ty:ty),* $(,)?) => {$(
            out.push('\n');
            if let Some(docs) = <$ty as TS>::docs() {
                out.push_str(&docs);
            }
            out.push_str("export ");
            out.push_str(&<$ty as TS>::decl(&cfg));
            out.push('\n');
        )*};
    }

    declare!(
        DocumentId,
        RequestId,
        PageSize,
        Rotation,
        Point,
        Rect,
        Quad,
        FindingKind,
        SecurityFinding,
        SecurityReport,
        DocumentInfo,
        RenderPageArgs,
        BlockedAction,
        LinkTarget,
        LinkId,
        PageLink,
        LinkArgs,
        OutlineLinkArgs,
        LinkPreview,
        OutlineItem,
        OutlineResult,
        SearchArgs,
        SearchHit,
        SearchEvent,
        ErrorCode,
        IpcError,
        OpenEvent,
    );

    let limits: [(&str, String); 17] = [
        ("maxPageCount", MAX_PAGE_COUNT.to_string()),
        ("maxPageSidePt", MAX_PAGE_SIDE_PT.to_string()),
        ("minRenderScale", MIN_RENDER_SCALE.to_string()),
        ("maxRenderScale", MAX_RENDER_SCALE.to_string()),
        ("maxRasterSidePx", MAX_RASTER_SIDE_PX.to_string()),
        ("maxRasterPixels", MAX_RASTER_PIXELS.to_string()),
        ("maxOutlineItems", MAX_OUTLINE_ITEMS.to_string()),
        ("maxOutlineDepth", MAX_OUTLINE_DEPTH.to_string()),
        ("maxLinksPerPage", MAX_LINKS_PER_PAGE.to_string()),
        ("maxUriBytes", MAX_URI_BYTES.to_string()),
        ("maxTextBytes", MAX_TEXT_BYTES.to_string()),
        ("maxQueryBytes", MAX_QUERY_BYTES.to_string()),
        ("maxSearchHits", MAX_SEARCH_HITS.to_string()),
        ("maxQuadsPerHit", MAX_QUADS_PER_HIT.to_string()),
        ("maxErrorMessageBytes", MAX_ERROR_MESSAGE_BYTES.to_string()),
        ("maxDisplayNameBytes", MAX_DISPLAY_NAME_BYTES.to_string()),
        ("protocolVersion", crate::PROTOCOL_VERSION.to_string()),
    ];
    out.push_str(
        "\n/** Limits enforced by the main process (crates/ipc_contract/src/limits.rs). */\n",
    );
    out.push_str("export const LIMITS = {\n");
    for (name, value) in limits {
        out.push_str(&format!("  {name}: {value},\n"));
    }
    out.push_str("} as const;\n");

    let magic = String::from_utf8_lossy(&RASTER_MAGIC);
    out.push_str(
        "\n/** Binary layout of `render_page` responses (crates/ipc_contract/src/raster.rs). */\n",
    );
    out.push_str("export const RASTER = {\n");
    out.push_str(&format!("  magic: \"{magic}\",\n"));
    out.push_str(&format!("  headerBytes: {RASTER_HEADER_BYTES},\n"));
    out.push_str(&format!("  formatRgba8: {RASTER_FORMAT_RGBA8},\n"));
    out.push_str("} as const;\n");
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generated_typescript_is_up_to_date() {
        let committed = std::fs::read_to_string(output_path())
            .unwrap_or_default()
            .replace("\r\n", "\n");
        assert!(
            committed == bindings(),
            "src/ipc/generated/contract.ts is out of date; run `pnpm ipc:generate`"
        );
    }

    #[test]
    fn frontend_types_carry_no_file_paths() {
        // Only look at declarations; doc comments may legitimately say "never a path".
        let code: String = bindings()
            .lines()
            .filter(|line| {
                let line = line.trim_start();
                !(line.starts_with("//") || line.starts_with("/*") || line.starts_with('*'))
            })
            .collect::<Vec<_>>()
            .join("\n")
            .to_lowercase();
        for forbidden in ["path", "dir", "filename", "file_name", "folder"] {
            assert!(
                !code.contains(forbidden),
                "frontend-visible types must not expose `{forbidden}` (AGENTS.md principle 4)"
            );
        }
    }
}
